name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a test stage
      - name: Test stage
        run: |
          python3 -c "import struct;print('Python arch:', 8 * struct.calcsize('P'))"
          pip install tox
          tox -c .

  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      # Builds a portable application
      - name: Application build
        run: .\build.ps1

      # Stores job artifacts
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: print-server
          path: dist/print_server
